### PR TITLE
useSelector: Allow optional compararison function

### PR DESCRIPTION
**Pull request by josepot**
I would like to add this commit to the PR so that it has [this suggestion](https://github.com/reduxjs/react-redux/pull/1288#issuecomment-493715499) from @markerikson

Thanks!

Changes:
- useSelector: Allow optional compararison function
- Export shallowEqual function

### CODE REVIEW

**Comment by perrin4869** [comment]
@josepot What do you think about the changes I proposed in the `react-redux` PR? `shallowEqual` is exported basically with the single use-case of using it as an argument of `useSelect`, so I think we might as well provide the actual hook rather than a generic comparison. But of course that's only if you and the react-redux maintaners agree

**Comment by josepot** [comment]
I don't know. I see pros and cons to both options.

I like the idea of having a hook-selector that's made for returning Objects, but it's also true that would increase the API surface, although exporting shallowEqual does that, too... So... :man_shrugging:

Having a hook that takes the equality function as a second arg is a more flexible approach that "works for everyone", but I'm not sure how I feel about that amount of "flexibility"... TBH my preference would be towards increasing the API surface in favor of specific and idiomatic hooks. Do one thing and do it well kinda approach.

About the exposure of `shallowEqual`, I actually think that the right thing to do would be to have a tiny library that everyone imports from which has that function... But since we don't have that library, it could be handy to get it from React-Redux. It's a poor argument, I know :sweat_smile: 

All that being said. I think that what's most important at this point is not to find the "best" solution, but a solution that we all feel comfortable with. So, I'm more than willing to compromise in favor of Mark Erikson's proposal.

**Comment by perrin4869** [comment]
hm... Let's wait and see what Mark Erikson says on the matter before proceeding then :)

**Comment by markerikson** [comment]
Awright, let's go ahead and merge this in.

**Comment by josepot** [comment]
Cmon @perrin4869 merge it, quickly! Before Tim comes back from Disney World... :smile:

**Pull request merged**
